/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.MedicineDAO;
import model.Medicine;
import dao.SupplierDAO;
import model.Supplier;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author kenisha
 */
public class MedicineForm extends javax.swing.JFrame {
private int selectedMedicineId = -1;
    /**
     * Creates new form MedicineForm
     */
    public MedicineForm() {
    initComponents();
    loadSuppliers();
    loadMedicines();

    }
    
    private void loadSuppliers() {

    SupplierDAO supplierDAO = new SupplierDAO();

    List<Supplier> suppliers = supplierDAO.getAllSuppliers();

    cmbSupplier.removeAllItems();

    for (Supplier supplier : suppliers) {
        cmbSupplier.addItem(
                supplier.getSupplierId() + " - " + supplier.getName());
    }
}
    private void loadMedicines() {

    MedicineDAO medicineDAO = new MedicineDAO();

    List<Medicine> medicines = medicineDAO.getAllMedicines();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblMedicines.getModel();

    model.setRowCount(0);

    for (Medicine medicine : medicines) {

        model.addRow(new Object[]{
            medicine.getMedicineId(),
            medicine.getName(),
            medicine.getCompany(),
            medicine.getMedicineType(),
            medicine.getPrice(),
            medicine.getQuantityInStock(),
            medicine.getReorderLevel(),
            medicine.getExpiryDate()
        });
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblReorder = new javax.swing.JLabel();
        txtReorder = new javax.swing.JTextField();
        lblExpiry = new javax.swing.JLabel();
        txtExpiry = new javax.swing.JTextField();
        lblSupplier = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cmbSupplier = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicines = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Medicine Management");

        lblName.setText("Medicine Name: ");

        lblCompany.setText("Company : ");

        lblType.setText("Medicine Type :");

        lblPrice.setText("Price :");

        lblQuantity.setText("Quantity in Stock :");

        lblReorder.setText("Reorder Level :");

        txtReorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReorderActionPerformed(evt);
            }
        });

        lblExpiry.setText("Expiry Date : ");

        lblSupplier.setText("Supplier ID :");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save Medicine");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Name", "Company", "Type", "Price", "Quantity", "Reorder Level", "Expiry Date"
            }
        ));
        tblMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicinesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedicines);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblReorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReorder, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtQuantity)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(37, 37, 37)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(txtType))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompany)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblType)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReorder))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiry)
                    .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnClear)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
String company = txtCompany.getText().trim();
String medicineType = txtType.getText().trim();
String expiryDate = txtExpiry.getText().trim();

if (name.isEmpty() || company.isEmpty() || medicineType.isEmpty()
        || txtPrice.getText().trim().isEmpty()
        || txtQuantity.getText().trim().isEmpty()
        || txtReorder.getText().trim().isEmpty()
        || expiryDate.isEmpty()
        || cmbSupplier.getSelectedItem() == null)  {

    JOptionPane.showMessageDialog(this,
            "Please fill in all fields.");
    return;
}

try {

    double price = Double.parseDouble(txtPrice.getText().trim());
    int quantity = Integer.parseInt(txtQuantity.getText().trim());
    int reorderLevel = Integer.parseInt(txtReorder.getText().trim());
    
    String selectedSupplier =
        cmbSupplier.getSelectedItem().toString();

int supplierId =
        Integer.parseInt(selectedSupplier.split(" - ")[0]);

    Medicine medicine = new Medicine();

    medicine.setName(name);
    medicine.setCompany(company);
    medicine.setMedicineType(medicineType);
    medicine.setPrice(price);
    medicine.setQuantityInStock(quantity);
    medicine.setReorderLevel(reorderLevel);
    medicine.setExpiryDate(expiryDate);
    medicine.setSupplierId(supplierId);

    MedicineDAO medicineDAO = new MedicineDAO();

    if (medicineDAO.addMedicine(medicine)) {

        JOptionPane.showMessageDialog(this,
                "Medicine added successfully!");

    } else {

        JOptionPane.showMessageDialog(this,
                "Could not add medicine.");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Please enter valid numbers for price, quantity, reorder level and supplier ID.");
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
txtCompany.setText("");
txtType.setText("");
txtPrice.setText("");
txtQuantity.setText("");
txtReorder.setText("");
txtExpiry.setText("");

if (cmbSupplier.getItemCount() > 0) {
    cmbSupplier.setSelectedIndex(0);
}
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReorderActionPerformed

    private void tblMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicinesMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblMedicines.getSelectedRow();

if (selectedRow != -1) {
    
    selectedMedicineId = Integer.parseInt(
        tblMedicines.getValueAt(selectedRow, 0).toString());

    txtName.setText(
            tblMedicines.getValueAt(selectedRow, 1).toString());

    txtCompany.setText(
            tblMedicines.getValueAt(selectedRow, 2).toString());

    txtType.setText(
            tblMedicines.getValueAt(selectedRow, 3).toString());

    txtPrice.setText(
            tblMedicines.getValueAt(selectedRow, 4).toString());

    txtQuantity.setText(
            tblMedicines.getValueAt(selectedRow, 5).toString());

    txtReorder.setText(
            tblMedicines.getValueAt(selectedRow, 6).toString());

    txtExpiry.setText(
            tblMedicines.getValueAt(selectedRow, 7).toString());
}
    }//GEN-LAST:event_tblMedicinesMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedMedicineId == -1) {

    JOptionPane.showMessageDialog(this,
            "Please select a medicine from the table first.");
    return;
}

String name = txtName.getText().trim();
String company = txtCompany.getText().trim();
String medicineType = txtType.getText().trim();
String expiryDate = txtExpiry.getText().trim();

if (name.isEmpty() || company.isEmpty() || medicineType.isEmpty()
        || txtPrice.getText().trim().isEmpty()
        || txtQuantity.getText().trim().isEmpty()
        || txtReorder.getText().trim().isEmpty()
        || expiryDate.isEmpty()
        || cmbSupplier.getSelectedItem() == null) {

    JOptionPane.showMessageDialog(this,
            "Please fill in all fields.");
    return;
}

try {

    double price = Double.parseDouble(txtPrice.getText().trim());
    int quantity = Integer.parseInt(txtQuantity.getText().trim());
    int reorderLevel = Integer.parseInt(txtReorder.getText().trim());

    String selectedSupplier =
            cmbSupplier.getSelectedItem().toString();

    int supplierId =
            Integer.parseInt(selectedSupplier.split(" - ")[0]);

    Medicine medicine = new Medicine();

    medicine.setMedicineId(selectedMedicineId);
    medicine.setName(name);
    medicine.setCompany(company);
    medicine.setMedicineType(medicineType);
    medicine.setPrice(price);
    medicine.setQuantityInStock(quantity);
    medicine.setReorderLevel(reorderLevel);
    medicine.setExpiryDate(expiryDate);
    medicine.setSupplierId(supplierId);

    MedicineDAO medicineDAO = new MedicineDAO();

    if (medicineDAO.updateMedicine(medicine)) {

        JOptionPane.showMessageDialog(this,
                "Medicine updated successfully!");

        loadMedicines();

txtName.setText("");
txtCompany.setText("");
txtType.setText("");
txtPrice.setText("");
txtQuantity.setText("");
txtReorder.setText("");
txtExpiry.setText("");

if (cmbSupplier.getItemCount() > 0) {
    cmbSupplier.setSelectedIndex(0);
}

selectedMedicineId = -1;

    } else {

        JOptionPane.showMessageDialog(this,
                "Could not update medicine.");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Please enter valid numbers for price, quantity and reorder level.");
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblExpiry;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReorder;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JTable tblMedicines;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtExpiry;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReorder;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
