/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.BillForm;
import dao.MedicineDAO;
import dao.SaleDAO;
import model.User;
import model.Medicine;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kenisha
 */
public class POSForm extends javax.swing.JFrame {
    private User loggedInUser;

    /**
     * Creates new form POSForm
     */
    public POSForm(User user) {
    initComponents();
    this.loggedInUser = user;
    loadMedicines();
}

public POSForm() {
    initComponents();
    loadMedicines();
}
    private void loadMedicines() {

    MedicineDAO medicineDAO = new MedicineDAO();

    List<Medicine> medicines = medicineDAO.getAllMedicines();

    cmbMedicine.removeAllItems();

    for (Medicine medicine : medicines) {
        cmbMedicine.addItem(medicine.getName());
    }
}
    
    private void calculateGrandTotal() {

    DefaultTableModel model =
            (DefaultTableModel) tblCart.getModel();

    double grandTotal = 0.0;

    for (int i = 0; i < model.getRowCount(); i++) {

        double total = Double.parseDouble(
                model.getValueAt(i, 4).toString());

        grandTotal += total;
    }

    lblGrandTotal.setText(
            String.format("Grand Total: R%.2f", grandTotal));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        cmbMedicine = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblGrandTotal = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("POINT OF SALE");

        lblMedicine.setText("Medicine :");

        cmbMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity :");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lblPrice.setText("Price :");

        lblTotal.setText("Total: ");

        btnClear.setText("Clear Cart");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Selected");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add to Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setResizable(false);
            tblCart.getColumnModel().getColumn(4).setResizable(false);
        }

        lblGrandTotal.setText("Grand Total: R0,00");

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addGap(165, 165, 165)
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGrandTotal)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(lblTitle))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicine)
                    .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(lblGrandTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout)
                    .addComponent(btnBack))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineActionPerformed
        // TODO add your handling code here:
        String selectedMedicine = (String) cmbMedicine.getSelectedItem();

    if (selectedMedicine == null) {
    return;
}

MedicineDAO medicineDAO = new MedicineDAO();
List<Medicine> medicines = medicineDAO.getAllMedicines();

for (Medicine medicine : medicines) {

    if (medicine.getName().equals(selectedMedicine)) {

        txtPrice.setText(String.format("%.2f", medicine.getPrice()));

        break;
    }
}
    }//GEN-LAST:event_cmbMedicineActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
        try {

    double price = Double.parseDouble(txtPrice.getText().trim());
    int quantity = Integer.parseInt(txtQuantity.getText().trim());

    double total = price * quantity;

    txtTotal.setText(String.format("%.2f", total));

} catch (NumberFormatException e) {

    txtTotal.setText("0.00");
}
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String medicineName = (String) cmbMedicine.getSelectedItem();

if (medicineName == null || medicineName.isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Please select a medicine.");
    return;
}

try {

    int quantity = Integer.parseInt(txtQuantity.getText().trim());
    double price = Double.parseDouble(txtPrice.getText().trim());
    double total = price * quantity;

    if (quantity <= 0) {
        JOptionPane.showMessageDialog(this,
                "Quantity must be greater than 0.");
        return;
    }

    // Find the selected medicine
    MedicineDAO medicineDAO = new MedicineDAO();
    List<Medicine> medicines = medicineDAO.getAllMedicines();

    int medicineId = -1;

    for (Medicine medicine : medicines) {
        if (medicine.getName().equals(medicineName)) {
            medicineId = medicine.getMedicineId();
            break;
        }
    }

    if (medicineId == -1) {
        JOptionPane.showMessageDialog(this,
                "Medicine could not be found.");
        return;
    }

    DefaultTableModel model =
            (DefaultTableModel) tblCart.getModel();

    model.addRow(new Object[]{
        medicineId,
        medicineName,
        quantity,
        String.format("%.2f", price),
        String.format("%.2f", total)
    });

    txtQuantity.setText("1");
    txtTotal.setText("0.00");

    calculateGrandTotal();

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Please enter a valid quantity.");
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCart.getSelectedRow();

if (selectedRow == -1) {

    JOptionPane.showMessageDialog(this,
            "Please select an item to remove.");

    return;
}

DefaultTableModel model =
        (DefaultTableModel) tblCart.getModel();

model.removeRow(selectedRow);

calculateGrandTotal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =
        (DefaultTableModel) tblCart.getModel();

model.setRowCount(0);

cmbMedicine.setSelectedIndex(-1);
txtQuantity.setText("1");
txtPrice.setText("0.00");
txtTotal.setText("0.00");

calculateGrandTotal();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =
        (DefaultTableModel) tblCart.getModel();

if (model.getRowCount() == 0) {
    JOptionPane.showMessageDialog(this,
            "Please add at least one item to the cart.");
    return;
}

double grandTotal = 0.0;

for (int i = 0; i < model.getRowCount(); i++) {
    double total = Double.parseDouble(
            model.getValueAt(i, 3).toString());

    grandTotal += total;
}

if (loggedInUser == null) {
    JOptionPane.showMessageDialog(this,
            "No logged-in user found.");
    return;
}

SaleDAO saleDAO = new SaleDAO();

int saleId = saleDAO.createSale(
        grandTotal,
        loggedInUser.getUserId()
);

if (saleId != -1) {

   

    boolean allItemsSaved = true;

    for (int i = 0; i < model.getRowCount(); i++) {

        int medicineId = Integer.parseInt(
                model.getValueAt(i, 0).toString());

        int quantitySold = Integer.parseInt(
                model.getValueAt(i, 2).toString());

        double priceAtSale = Double.parseDouble(
                model.getValueAt(i, 4).toString());

        boolean itemSaved = saleDAO.addSaleItem(
                saleId,
                medicineId,
                quantitySold,
                priceAtSale
        );
        
        if (itemSaved) {

    MedicineDAO medicineDAO = new MedicineDAO();

    boolean stockUpdated =
            medicineDAO.reduceStock(medicineId, quantitySold);

    if (!stockUpdated) {
        allItemsSaved = false;
        break;
    }
}

        if (!itemSaved) {
            allItemsSaved = false;
            break;
        }
    }

    if (allItemsSaved) {

    JOptionPane.showMessageDialog(this,
            "Sale completed successfully!");
    new BillForm(saleId, grandTotal).setVisible(true);
    this.dispose();
    
    } else {
        JOptionPane.showMessageDialog(this,
                "Sale was created, but some items could not be saved.");
    }

} else {

    JOptionPane.showMessageDialog(this,
            "Could not create the sale.");
}
        
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
