/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.SaleDAO;
import dao.ReportDAO;

import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author kenisha
 */
public class ReportsForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
        loadSalesChart();
        loadTopMedicinesChart();
        
        ReportDAO reportDAO = new ReportDAO();

    double totalSales = reportDAO.getTotalSales();

    lblTotalSales.setText(
            String.format("Total Sales: R%.2f", totalSales));
    int numberOfSales = reportDAO.getNumberOfSales();

lblNumberOfSales.setText(
        "Number of Sales: " + numberOfSales);

int medicinesSold = reportDAO.getMedicinesSold();

lblMedicineSold.setText(
        "Medicines Sold: " + medicinesSold);

int lowStockItems = reportDAO.getLowStockItems();

lblLowStock.setText(
        "Low Stock Items: " + lowStockItems);

loadSales();
    }
    
    
    
    private void loadSales() {

    ReportDAO reportDAO = new ReportDAO();

    ResultSet resultSet = reportDAO.getAllSales();

    DefaultTableModel model =
            (DefaultTableModel) tblSales.getModel();

    model.setRowCount(0);

    try {

        while (resultSet != null && resultSet.next()) {

            int saleId =
                    resultSet.getInt("sale_id");

            String saleDate =
                    resultSet.getString("sale_date");

            double totalAmount =
                    resultSet.getDouble("total_amount");

            int userId =
                    resultSet.getInt("user_id");

            model.addRow(new Object[]{
                saleId,
                saleDate,
                String.format("R%.2f", totalAmount),
                userId,
                "User " + userId
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Could not load sales.");
    }
}
    private void loadSalesChart() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    SaleDAO saleDAO = new SaleDAO();
ResultSet resultSet = saleDAO.getMonthlySales();

try {
    while (resultSet != null && resultSet.next()) {
        String month = resultSet.getString("month");
        double totalSales = resultSet.getDouble("total_sales");

        dataset.addValue(totalSales, "Sales", month);
    }
} catch (SQLException e) {
    System.out.println("Error loading sales chart: " + e.getMessage());
}

    JFreeChart chart = ChartFactory.createLineChart(
            "Monthly Sales",
            "Month",
            "Sales (R)",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(550, 280));

    pnlSalesChart.removeAll();
    pnlSalesChart.setLayout(new java.awt.BorderLayout());
    pnlSalesChart.add(chartPanel, java.awt.BorderLayout.CENTER);
    pnlSalesChart.revalidate();
    pnlSalesChart.repaint();
}
    
    private void loadTopMedicinesChart() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    SaleDAO saleDAO = new SaleDAO();
    ResultSet resultSet = saleDAO.getTopSellingMedicines();

    try {
        while (resultSet != null && resultSet.next()) {
            String medicineName = resultSet.getString("name");
            int totalSold = resultSet.getInt("total_sold");

            dataset.addValue(totalSold, "Units Sold", medicineName);
        }
    } catch (SQLException e) {
        System.out.println("Error loading top medicines chart: " + e.getMessage());
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Top-Selling Medicines",
            "Medicine",
            "Units Sold",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(550, 280));

    pnlTopMedicinesChart.removeAll();
    pnlTopMedicinesChart.setLayout(new java.awt.BorderLayout());
    pnlTopMedicinesChart.add(chartPanel, java.awt.BorderLayout.CENTER);
    pnlTopMedicinesChart.revalidate();
    pnlTopMedicinesChart.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblNumberOfSales = new javax.swing.JLabel();
        lblMedicineSold = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlSalesChart = new javax.swing.JPanel();
        pnlTopMedicinesChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 255));
        lblTitle.setText("PHARMACY REPORTS");

        lblTotalSales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTotalSales.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalSales.setText("Total Sales : R0.00");

        lblNumberOfSales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNumberOfSales.setForeground(new java.awt.Color(0, 0, 0));
        lblNumberOfSales.setText("Number of Sales : 0");

        lblMedicineSold.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblMedicineSold.setForeground(new java.awt.Color(0, 0, 0));
        lblMedicineSold.setText("Medicine Sold : 0");

        lblLowStock.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblLowStock.setForeground(new java.awt.Color(0, 0, 0));
        lblLowStock.setText("Low Stock Items: 0");

        tblSales.setBackground(new java.awt.Color(0, 0, 0));
        tblSales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tblSales.setForeground(new java.awt.Color(255, 102, 255));
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sale ID", "Date", "Total Amount", "User ID", "Cashier"
            }
        ));
        jScrollPane1.setViewportView(tblSales);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 102, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 102, 255));
        btnRefresh.setText("Refresh Reports");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 255));
        jLabel1.setText("HealthFirst Pharmacy Performance Overview");

        jLabel11.setText("===============================================================================================================================================================================================================================================");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SALES & INVENTORY SUMMARY");

        jLabel3.setForeground(new java.awt.Color(255, 153, 255));
        jLabel3.setText("Monitor pharmacy sales, medicines sold and inventory levels at a glance.");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RECENT SALES TRANSACTIONS");

        javax.swing.GroupLayout pnlSalesChartLayout = new javax.swing.GroupLayout(pnlSalesChart);
        pnlSalesChart.setLayout(pnlSalesChartLayout);
        pnlSalesChartLayout.setHorizontalGroup(
            pnlSalesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        pnlSalesChartLayout.setVerticalGroup(
            pnlSalesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTopMedicinesChartLayout = new javax.swing.GroupLayout(pnlTopMedicinesChart);
        pnlTopMedicinesChart.setLayout(pnlTopMedicinesChartLayout);
        pnlTopMedicinesChartLayout.setHorizontalGroup(
            pnlTopMedicinesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        pnlTopMedicinesChartLayout.setVerticalGroup(
            pnlTopMedicinesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSalesChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberOfSales, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicineSold, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(pnlTopMedicinesChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalSales)
                        .addGap(23, 23, 23)
                        .addComponent(lblNumberOfSales)
                        .addGap(29, 29, 29)
                        .addComponent(lblMedicineSold)
                        .addGap(29, 29, 29)
                        .addComponent(lblLowStock))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSalesChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTopMedicinesChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
                                                  
    ReportDAO reportDAO = new ReportDAO();

    double totalSales = reportDAO.getTotalSales();

    lblTotalSales.setText(
            String.format("Total Sales: R%.2f", totalSales));

    int numberOfSales = reportDAO.getNumberOfSales();

    lblNumberOfSales.setText(
            "Number of Sales: " + numberOfSales);

    int medicinesSold = reportDAO.getMedicinesSold();

    lblMedicineSold.setText(
            "Medicines Sold: " + medicinesSold);

    int lowStockItems = reportDAO.getLowStockItems();

    lblLowStock.setText(
            "Low Stock Items: " + lowStockItems);

    loadSales();

    JOptionPane.showMessageDialog(this,
            "Reports refreshed successfully!");

    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblMedicineSold;
    private javax.swing.JLabel lblNumberOfSales;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JPanel pnlSalesChart;
    private javax.swing.JPanel pnlTopMedicinesChart;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables
}
